<?php

namespace AppBundle\Repository;

/**
 * AlunoMiniCursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlunoMiniCursoRepository extends \Doctrine\ORM\EntityRepository
{
}
