<?php

namespace AppBundle\Repository;

/**
 * MiniCursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MiniCursoRepository extends \Doctrine\ORM\EntityRepository
{
}
