<?php

namespace AppBundle\Repository;

/**
 * TrabalhosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrabalhosRepository extends \Doctrine\ORM\EntityRepository
{
}
